[Service]
RuntimeDirectory=caddy
RuntimeDirectoryMode=0750
ExecStart=
ExecStart=/usr/bin/caddy run --environ --config /etc/caddy/Caddyfile.root
ExecReload=
ExecReload=/usr/bin/caddy reload --config /etc/caddy/Caddyfile.root --address unix//run/caddy/admin.sock --force
