"""Authoritative structural contract for the HireSense PostgreSQL schema."""

TABLE_COLUMNS = {
    "sectors": {
        "id", "name", "description", "email_alias", "created_at", "updated_at",
    },
    "users": {
        "id", "email", "password_hash", "role", "name", "sector_id",
        "created_at", "updated_at",
    },
    "candidates": {
        "id", "name", "email", "phone", "resume_path", "parsed_skills",
        "years_experience", "education", "match_score", "shortlist_status",
        "pros", "cons", "status", "created_at", "updated_at",
        "best_match_job_id", "sector_id",
    },
    "job_descriptions": {
        "id", "title", "description", "required_skills", "min_experience",
        "department", "work_mode", "created_at", "updated_at", "sector_id",
        "status", "preferred_skills", "salary_range", "employment_type",
        "experience_level", "closes_at", "created_by", "max_experience",
        "role_complexity_level",
    },
    "scheduled_assessments": {
        "id", "candidate_id", "interviewer_id", "scheduled_time", "status",
        "created_at", "updated_at", "access_token_hash", "started_at",
        "is_technical_role", "questions_data", "job_id", "proctor_id",
    },
    "assessments": {
        "id", "candidate_id", "job_id", "technical_score",
        "psychometric_score", "overall_score", "automated_recommendation",
        "automated_rationale", "recommended_next_step", "final_decision",
        "final_rationale",
        "proctoring_violations", "status", "scheduled_assessment_id",
        "started_at", "completed_at", "created_at",
        "questions_data", "time_elapsed_seconds",
    },
    "mcq_responses": {
        "id", "assessment_id", "question_id", "selected_answer", "is_correct",
        "time_spent", "created_at",
    },
    "coding_submissions": {
        "id", "assessment_id", "problem_id", "language", "code",
        "test_cases_passed", "total_test_cases", "submitted_at",
    },
    "psychometric_responses": {
        "id", "assessment_id", "question_id", "trait", "score",
        "scenario_response", "created_at",
    },
    "proctoring_violations": {
        "id", "assessment_id", "violation_type", "description",
        "screenshot_path", "timestamp", "severity",
    },
    "email_logs": {
        "id", "recipient_email", "recipient_name", "email_type", "subject",
        "status", "error_message", "sent_at",
    },
    "candidate_job_matches": {
        "id", "candidate_id", "job_id", "match_score", "skill_match_score",
        "experience_match_score", "ai_reasoning", "status", "matched_at",
        "reviewed_by", "reviewed_at",
    },
    "audit_log": {
        "id", "user_id", "user_email", "action", "entity_type", "entity_id",
        "details", "ip_address", "created_at",
    },
    "custom_question_bank": {
        "id", "original_filename", "file_path", "questions_text",
        "parsed_questions", "uploaded_by", "description", "tags", "is_active",
        "created_at", "updated_at",
    },
}

APP_TABLES = set(TABLE_COLUMNS)

FORBIDDEN_TABLES = {
    "admin_audit_log",
    "proctoring_events",
    "questions",
    "sector_email_configs",
}

FORBIDDEN_COLUMNS = {
    ("assessments", "decision"),
    ("assessments", "hiring_recommendation"),
    ("assessments", "rationale"),
    ("candidates", "job_id"),
    ("candidates", "parsed_skills_json"),
    ("coding_submissions", "error_message"),
    ("coding_submissions", "execution_time"),
    ("custom_question_bank", "filename"),
    ("job_descriptions", "created_by_id"),
    ("job_descriptions", "location"),
    ("proctoring_violations", "screenshot_url"),
    ("scheduled_assessments", "assessment_id"),
    ("scheduled_assessments", "access_token"),
    ("scheduled_assessments", "is_streaming"),
    ("scheduled_assessments", "stream_ended_at"),
    ("scheduled_assessments", "stream_started_at"),
    ("users", "permissions"),
}

TIMESTAMP_COLUMNS = {
    ("assessments", "started_at"),
    ("assessments", "completed_at"),
    ("assessments", "created_at"),
    ("audit_log", "created_at"),
    ("candidate_job_matches", "matched_at"),
    ("candidate_job_matches", "reviewed_at"),
    ("candidates", "created_at"),
    ("candidates", "updated_at"),
    ("coding_submissions", "submitted_at"),
    ("custom_question_bank", "created_at"),
    ("custom_question_bank", "updated_at"),
    ("email_logs", "sent_at"),
    ("job_descriptions", "created_at"),
    ("job_descriptions", "updated_at"),
    ("job_descriptions", "closes_at"),
    ("mcq_responses", "created_at"),
    ("proctoring_violations", "timestamp"),
    ("psychometric_responses", "created_at"),
    ("scheduled_assessments", "scheduled_time"),
    ("scheduled_assessments", "created_at"),
    ("scheduled_assessments", "updated_at"),
    ("scheduled_assessments", "started_at"),
    ("sectors", "created_at"),
    ("sectors", "updated_at"),
    ("users", "created_at"),
    ("users", "updated_at"),
}

REQUIRED_UNIQUE_INDEXES = {
    "idx_assessments_scheduled_unique",
    "idx_candidate_job_matches_candidate_job_unique",
    "idx_candidates_email_lower_unique",
    "idx_coding_assessment_problem_unique",
    "idx_mcq_assessment_question_unique",
    "idx_psychometric_assessment_question_unique",
    "idx_scheduled_assessments_access_token_hash_unique",
    "idx_scheduled_assessments_candidate_active_unique",
    "idx_users_email_lower_unique",
}

REQUIRED_INDEXES = REQUIRED_UNIQUE_INDEXES | {
    "idx_assessments_candidate",
    "idx_assessments_job",
    "idx_assessments_status",
    "idx_audit_log_action",
    "idx_audit_log_created",
    "idx_audit_log_entity",
    "idx_audit_log_user",
    "idx_candidate_job_matches_job",
    "idx_candidate_job_matches_reviewed_by",
    "idx_candidate_job_matches_score",
    "idx_candidates_best_job",
    "idx_candidates_sector",
    "idx_candidates_shortlist_status",
    "idx_candidates_status",
    "idx_custom_question_bank_uploaded_by",
    "idx_email_logs_recipient",
    "idx_email_logs_status",
    "idx_email_logs_type",
    "idx_job_descriptions_created_by",
    "idx_job_descriptions_level",
    "idx_job_descriptions_sector",
    "idx_job_descriptions_status",
    "idx_proctoring_violations_assessment",
    "idx_scheduled_assessments_candidate",
    "idx_scheduled_assessments_interviewer",
    "idx_scheduled_assessments_job",
    "idx_scheduled_assessments_proctor",
    "idx_scheduled_assessments_time",
    "idx_users_role",
    "idx_users_sector",
}

FORBIDDEN_INDEXES = {
    "idx_candidate_job_matches_candidate",
    "idx_candidates_email",
    "idx_coding_assessment",
    "idx_mcq_assessment",
    "idx_psychometric_assessment",
    "idx_scheduled_assessments_token",
    "idx_scheduled_assessments_access_token_unique",
    "idx_users_email",
}

REQUIRED_CHECK_CONSTRAINTS = {
    "assessments_final_decision_check",
    "assessments_proctoring_violations_check",
    "assessments_scores_check",
    "assessments_status_check",
    "assessments_time_elapsed_check",
    "candidate_job_matches_scores_check",
    "candidate_job_matches_status_check",
    "candidates_match_score_check",
    "candidates_shortlist_status_check",
    "candidates_status_check",
    "candidates_years_experience_check",
    "coding_submissions_counts_check",
    "email_logs_status_check",
    "job_descriptions_experience_check",
    "job_descriptions_experience_level_check",
    "job_descriptions_status_check",
    "job_descriptions_type_check",
    "job_descriptions_work_mode_check",
    "mcq_responses_question_check",
    "mcq_responses_time_check",
    "proctoring_violations_severity_check",
    "psychometric_responses_question_check",
    "psychometric_responses_score_check",
    "scheduled_assessments_status_check",
    "scheduled_assessments_access_token_hash_check",
    "users_role_check",
    "users_sector_scope_check",
}

REQUIRED_FOREIGN_KEYS = {
    ("assessments", "candidate_id", "candidates", "c"),
    ("assessments", "job_id", "job_descriptions", "n"),
    ("assessments", "scheduled_assessment_id", "scheduled_assessments", "n"),
    ("audit_log", "user_id", "users", "n"),
    ("candidate_job_matches", "candidate_id", "candidates", "c"),
    ("candidate_job_matches", "job_id", "job_descriptions", "c"),
    ("candidate_job_matches", "reviewed_by", "users", "n"),
    ("candidates", "best_match_job_id", "job_descriptions", "n"),
    ("candidates", "sector_id", "sectors", "n"),
    ("coding_submissions", "assessment_id", "assessments", "c"),
    ("custom_question_bank", "uploaded_by", "users", "n"),
    ("job_descriptions", "created_by", "users", "n"),
    ("job_descriptions", "sector_id", "sectors", "n"),
    ("mcq_responses", "assessment_id", "assessments", "c"),
    ("proctoring_violations", "assessment_id", "assessments", "c"),
    ("psychometric_responses", "assessment_id", "assessments", "c"),
    ("scheduled_assessments", "candidate_id", "candidates", "c"),
    ("scheduled_assessments", "interviewer_id", "users", "r"),
    ("scheduled_assessments", "job_id", "job_descriptions", "n"),
    ("scheduled_assessments", "proctor_id", "users", "n"),
    ("users", "sector_id", "sectors", "r"),
}

REQUIRED_NOT_NULL_COLUMNS = {
    (table_name, "id") for table_name in APP_TABLES
} | {
    ("assessments", "candidate_id"),
    ("assessments", "created_at"),
    ("assessments", "proctoring_violations"),
    ("assessments", "status"),
    ("assessments", "time_elapsed_seconds"),
    ("audit_log", "action"),
    ("audit_log", "created_at"),
    ("candidate_job_matches", "candidate_id"),
    ("candidate_job_matches", "experience_match_score"),
    ("candidate_job_matches", "job_id"),
    ("candidate_job_matches", "match_score"),
    ("candidate_job_matches", "matched_at"),
    ("candidate_job_matches", "skill_match_score"),
    ("candidate_job_matches", "status"),
    ("candidates", "created_at"),
    ("candidates", "email"),
    ("candidates", "name"),
    ("candidates", "phone"),
    ("candidates", "resume_path"),
    ("candidates", "status"),
    ("candidates", "updated_at"),
    ("coding_submissions", "assessment_id"),
    ("coding_submissions", "code"),
    ("coding_submissions", "language"),
    ("coding_submissions", "problem_id"),
    ("coding_submissions", "submitted_at"),
    ("coding_submissions", "test_cases_passed"),
    ("coding_submissions", "total_test_cases"),
    ("custom_question_bank", "created_at"),
    ("custom_question_bank", "file_path"),
    ("custom_question_bank", "is_active"),
    ("custom_question_bank", "original_filename"),
    ("custom_question_bank", "questions_text"),
    ("custom_question_bank", "updated_at"),
    ("email_logs", "email_type"),
    ("email_logs", "recipient_email"),
    ("email_logs", "recipient_name"),
    ("email_logs", "sent_at"),
    ("email_logs", "status"),
    ("email_logs", "subject"),
    ("job_descriptions", "created_at"),
    ("job_descriptions", "employment_type"),
    ("job_descriptions", "experience_level"),
    ("job_descriptions", "min_experience"),
    ("job_descriptions", "role_complexity_level"),
    ("job_descriptions", "status"),
    ("job_descriptions", "title"),
    ("job_descriptions", "updated_at"),
    ("job_descriptions", "work_mode"),
    ("mcq_responses", "assessment_id"),
    ("mcq_responses", "created_at"),
    ("mcq_responses", "question_id"),
    ("mcq_responses", "selected_answer"),
    ("proctoring_violations", "assessment_id"),
    ("proctoring_violations", "severity"),
    ("proctoring_violations", "timestamp"),
    ("proctoring_violations", "violation_type"),
    ("psychometric_responses", "assessment_id"),
    ("psychometric_responses", "created_at"),
    ("psychometric_responses", "question_id"),
    ("psychometric_responses", "trait"),
    ("scheduled_assessments", "access_token_hash"),
    ("scheduled_assessments", "candidate_id"),
    ("scheduled_assessments", "created_at"),
    ("scheduled_assessments", "interviewer_id"),
    ("scheduled_assessments", "is_technical_role"),
    ("scheduled_assessments", "scheduled_time"),
    ("scheduled_assessments", "status"),
    ("scheduled_assessments", "updated_at"),
    ("sectors", "created_at"),
    ("sectors", "name"),
    ("sectors", "updated_at"),
    ("users", "created_at"),
    ("users", "email"),
    ("users", "name"),
    ("users", "password_hash"),
    ("users", "role"),
    ("users", "updated_at"),
}
