-- Migration: Sector-based access control and skillset enhancements
-- Date: 2026-02-05
-- Description: Adds sector support, role enhancements, audit logging, and skill management

-- ============================================================================
-- 1. ADD SECTOR FIELDS TO EXISTING TABLES
-- ============================================================================

-- Add sector to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS sector TEXT;
CREATE INDEX IF NOT EXISTS idx_users_sector ON users(sector);

-- Add sector to candidates table
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS sector TEXT;
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS skills JSONB DEFAULT '[]'::jsonb;
CREATE INDEX IF NOT EXISTS idx_candidates_sector ON candidates(sector);
CREATE INDEX IF NOT EXISTS idx_candidates_skills ON candidates USING GIN(skills);

-- Add sector and preferred_skills to job_descriptions
ALTER TABLE job_descriptions ADD COLUMN IF NOT EXISTS sector TEXT;
ALTER TABLE job_descriptions ADD COLUMN IF NOT EXISTS preferred_skills TEXT;
CREATE INDEX IF NOT EXISTS idx_job_descriptions_sector ON job_descriptions(sector);

-- ============================================================================
-- 2. CREATE SECTOR EMAIL CONFIGURATIONS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS sector_email_configs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sector TEXT NOT NULL UNIQUE,
    email_address TEXT NOT NULL,
    display_name TEXT NOT NULL,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sector_email_configs_sector ON sector_email_configs(sector);
CREATE INDEX IF NOT EXISTS idx_sector_email_configs_active ON sector_email_configs(is_active);

-- Insert default sector email configurations
INSERT INTO sector_email_configs (sector, email_address, display_name) 
VALUES 
    ('engineering', 'eng@cygnusa.com', 'Engineering Department'),
    ('sales', 'sales@cygnusa.com', 'Sales Department'),
    ('marketing', 'marketing@cygnusa.com', 'Marketing Department'),
    ('hr', 'hr@cygnusa.com', 'HR Department')
ON CONFLICT (sector) DO NOTHING;

-- ============================================================================
-- 3. CREATE AUDIT LOGS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS audit_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER,
    user_email TEXT NOT NULL,
    action TEXT NOT NULL,
    resource_type TEXT NOT NULL,
    resource_id INTEGER,
    details JSONB,
    ip_address TEXT,
    user_agent TEXT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id ON audit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON audit_logs(action);
CREATE INDEX IF NOT EXISTS idx_audit_logs_resource_type ON audit_logs(resource_type);
CREATE INDEX IF NOT EXISTS idx_audit_logs_timestamp ON audit_logs(timestamp);

-- ============================================================================
-- 4. UPDATE EMAIL LOGS TO TRACK SENDER
-- ============================================================================

ALTER TABLE email_logs ADD COLUMN IF NOT EXISTS sender_user_id INTEGER;
ALTER TABLE email_logs ADD COLUMN IF NOT EXISTS sender_email TEXT;
ALTER TABLE email_logs ADD COLUMN IF NOT EXISTS sector TEXT;

ALTER TABLE email_logs
    ADD CONSTRAINT fk_email_logs_sender
    FOREIGN KEY (sender_user_id) REFERENCES users(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_email_logs_sender ON email_logs(sender_user_id);
CREATE INDEX IF NOT EXISTS idx_email_logs_sector ON email_logs(sector);

-- ============================================================================
-- 5. ADD ROLE VALIDATION CHECK
-- ============================================================================

-- Note: Role validation will be enforced at application level
-- Valid roles: 'super_admin', 'sector_admin', 'recruiter', 'interviewer', 'admin', 'proctor'

COMMENT ON COLUMN users.role IS 'Valid roles: super_admin, sector_admin, recruiter, interviewer, admin, proctor';
COMMENT ON COLUMN users.sector IS 'Sector assignment for sector-specific roles (sector_admin, recruiter)';
COMMENT ON COLUMN candidates.sector IS 'Target sector for the candidate application';
COMMENT ON COLUMN candidates.skills IS 'JSON array of candidate skills provided during application';
COMMENT ON COLUMN job_descriptions.sector IS 'Sector for the job posting';
COMMENT ON COLUMN job_descriptions.preferred_skills IS 'Comma-separated list of preferred (non-required) skills';
