-- Migration: Add Sectors and Enhanced Job Postings
-- This migration adds sector-based organization, enhanced job postings with skills,
-- and automatic candidate-job matching capabilities

-- ============================================================================
--                           SECTORS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS sectors (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    email TEXT NOT NULL, -- sector-specific email (e.g., eng@company.com, sales@company.com)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sectors_name ON sectors(name);

-- Insert default sectors
INSERT INTO sectors (name, description, email) VALUES
    ('Engineering', 'Software Development and Engineering roles', 'eng@company.com'),
    ('Sales', 'Sales and Business Development roles', 'sales@company.com'),
    ('Marketing', 'Marketing and Communications roles', 'marketing@company.com'),
    ('Operations', 'Operations and Supply Chain roles', 'ops@company.com'),
    ('HR', 'Human Resources roles', 'hr@company.com'),
    ('Finance', 'Finance and Accounting roles', 'finance@company.com')
ON CONFLICT (name) DO NOTHING;

-- ============================================================================
--                           ENHANCE USERS TABLE FOR SECTOR-BASED ACCESS
-- ============================================================================

-- Add sector_id and enhanced role to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS sector_id INTEGER REFERENCES sectors(id) ON DELETE SET NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_super_admin BOOLEAN DEFAULT false;

-- Create index on sector_id for faster queries
CREATE INDEX IF NOT EXISTS idx_users_sector ON users(sector_id);

-- Update existing admins to be super admins
UPDATE users SET is_super_admin = true WHERE role = 'admin';

-- ============================================================================
--                           ENHANCE JOB DESCRIPTIONS TABLE
-- ============================================================================

-- Add new columns for enhanced job postings
ALTER TABLE job_descriptions ADD COLUMN IF NOT EXISTS sector_id INTEGER REFERENCES sectors(id) ON DELETE SET NULL;
ALTER TABLE job_descriptions ADD COLUMN IF NOT EXISTS required_skills_json JSONB DEFAULT '[]'::jsonb;
ALTER TABLE job_descriptions ADD COLUMN IF NOT EXISTS preferred_skills_json JSONB DEFAULT '[]'::jsonb;
ALTER TABLE job_descriptions ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active'; -- active, closed, draft
ALTER TABLE job_descriptions ADD COLUMN IF NOT EXISTS created_by INTEGER REFERENCES users(id) ON DELETE SET NULL;

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_job_descriptions_sector ON job_descriptions(sector_id);
CREATE INDEX IF NOT EXISTS idx_job_descriptions_status ON job_descriptions(status);
CREATE INDEX IF NOT EXISTS idx_job_descriptions_required_skills ON job_descriptions USING GIN (required_skills_json);
CREATE INDEX IF NOT EXISTS idx_job_descriptions_preferred_skills ON job_descriptions USING GIN (preferred_skills_json);

-- ============================================================================
--                           ENHANCE CANDIDATES TABLE
-- ============================================================================

-- Add job_id to candidates for automatic matching
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS job_id INTEGER REFERENCES job_descriptions(id) ON DELETE SET NULL;
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS parsed_skills_json JSONB DEFAULT '[]'::jsonb;
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS auto_matched_job_id INTEGER REFERENCES job_descriptions(id) ON DELETE SET NULL;
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS match_confidence REAL DEFAULT 0; -- 0-100 confidence score for auto-match

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_candidates_job ON candidates(job_id);
CREATE INDEX IF NOT EXISTS idx_candidates_auto_matched_job ON candidates(auto_matched_job_id);
CREATE INDEX IF NOT EXISTS idx_candidates_parsed_skills ON candidates USING GIN (parsed_skills_json);

-- ============================================================================
--                           AUDIT TRAIL TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS audit_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    user_email TEXT NOT NULL,
    action TEXT NOT NULL, -- e.g., 'create_job', 'send_email', 'update_candidate', 'delete_user'
    entity_type TEXT NOT NULL, -- e.g., 'job_posting', 'candidate', 'user', 'email'
    entity_id INTEGER,
    details JSONB, -- Store additional context as JSON
    ip_address TEXT,
    user_agent TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for audit log queries
CREATE INDEX IF NOT EXISTS idx_audit_logs_user ON audit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON audit_logs(action);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity ON audit_logs(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs(created_at);

-- ============================================================================
--                           EMAIL SENDER TRACKING
-- ============================================================================

-- Add sender tracking to email_logs
ALTER TABLE email_logs ADD COLUMN IF NOT EXISTS sender_email TEXT;
ALTER TABLE email_logs ADD COLUMN IF NOT EXISTS sent_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE email_logs ADD COLUMN IF NOT EXISTS sector_id INTEGER REFERENCES sectors(id) ON DELETE SET NULL;

-- Create index
CREATE INDEX IF NOT EXISTS idx_email_logs_sender ON email_logs(sent_by_user_id);
CREATE INDEX IF NOT EXISTS idx_email_logs_sector ON email_logs(sector_id);

-- ============================================================================
--                           CANDIDATE-JOB MATCHING TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS candidate_job_matches (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id INTEGER NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
    job_id INTEGER NOT NULL REFERENCES job_descriptions(id) ON DELETE CASCADE,
    match_score REAL NOT NULL DEFAULT 0, -- 0-100 matching score
    required_skills_matched INTEGER DEFAULT 0,
    required_skills_total INTEGER DEFAULT 0,
    preferred_skills_matched INTEGER DEFAULT 0,
    preferred_skills_total INTEGER DEFAULT 0,
    experience_match BOOLEAN DEFAULT false,
    matching_details JSONB, -- Detailed breakdown of matching
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(candidate_id, job_id)
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_candidate_job_matches_candidate ON candidate_job_matches(candidate_id);
CREATE INDEX IF NOT EXISTS idx_candidate_job_matches_job ON candidate_job_matches(job_id);
CREATE INDEX IF NOT EXISTS idx_candidate_job_matches_score ON candidate_job_matches(match_score DESC);

-- ============================================================================
--                           VIEWS FOR ENHANCED QUERIES
-- ============================================================================

-- View for candidate with best job match
CREATE OR REPLACE VIEW candidates_with_best_match AS
SELECT 
    c.*,
    cjm.job_id as best_match_job_id,
    cjm.match_score as best_match_score,
    jd.title as best_match_job_title,
    jd.department as best_match_department,
    s.name as best_match_sector
FROM candidates c
LEFT JOIN LATERAL (
    SELECT job_id, match_score
    FROM candidate_job_matches
    WHERE candidate_id = c.id
    ORDER BY match_score DESC
    LIMIT 1
) cjm ON true
LEFT JOIN job_descriptions jd ON cjm.job_id = jd.id
LEFT JOIN sectors s ON jd.sector_id = s.id;

-- View for job postings with candidate count
CREATE OR REPLACE VIEW jobs_with_candidate_counts AS
SELECT 
    jd.*,
    s.name as sector_name,
    s.email as sector_email,
    u.name as created_by_name,
    COUNT(DISTINCT c.id) as applied_candidates_count,
    COUNT(DISTINCT cjm.candidate_id) as matched_candidates_count,
    AVG(cjm.match_score) as avg_match_score
FROM job_descriptions jd
LEFT JOIN sectors s ON jd.sector_id = s.id
LEFT JOIN users u ON jd.created_by = u.id
LEFT JOIN candidates c ON c.job_id = jd.id
LEFT JOIN candidate_job_matches cjm ON cjm.job_id = jd.id
GROUP BY jd.id, s.name, s.email, u.name;

-- ============================================================================
--                           COMMENTS
-- ============================================================================

COMMENT ON TABLE sectors IS 'Organizational sectors/departments for role-based access control';
COMMENT ON TABLE audit_logs IS 'Audit trail for all system actions and email sends';
COMMENT ON TABLE candidate_job_matches IS 'Stores matching scores between candidates and job postings';
COMMENT ON COLUMN users.sector_id IS 'Links user to a specific sector for access control';
COMMENT ON COLUMN users.is_super_admin IS 'Super admins have access to all sectors';
COMMENT ON COLUMN job_descriptions.required_skills_json IS 'Array of required skills for the job';
COMMENT ON COLUMN job_descriptions.preferred_skills_json IS 'Array of preferred (nice-to-have) skills';
COMMENT ON COLUMN candidates.auto_matched_job_id IS 'Best matching job based on AI analysis';
COMMENT ON COLUMN candidates.match_confidence IS 'Confidence score (0-100) for the auto-match';
