-- Migration: Add Dashboard Features and Job Management
-- This migration adds support for:
-- 1. Admin Dashboard features (Job management, Question Bank, Email Templates)
-- 2. Interviewer Job Postings with AI refinement
-- 3. Proctor Dashboard enhancements
-- 4. Enhanced scoring and benchmarking

-- ============================================================================
-- 1. ENHANCED JOB DESCRIPTIONS TABLE
-- ============================================================================

-- Add new columns to job_descriptions
ALTER TABLE job_descriptions
ADD COLUMN IF NOT EXISTS created_by_id INTEGER,
ADD COLUMN IF NOT EXISTS ai_refined_description TEXT,
ADD COLUMN IF NOT EXISTS ideal_candidate_profile TEXT,
ADD COLUMN IF NOT EXISTS role_complexity_level TEXT DEFAULT 'intermediate',
ADD COLUMN IF NOT EXISTS skill_taxonomy TEXT,
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active',
ADD COLUMN IF NOT EXISTS is_archived BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS last_modified_by_id INTEGER,
ADD CONSTRAINT fk_job_created_by FOREIGN KEY (created_by_id) REFERENCES users(id) ON DELETE SET NULL,
ADD CONSTRAINT fk_job_modified_by FOREIGN KEY (last_modified_by_id) REFERENCES users(id) ON DELETE SET NULL;

-- ============================================================================
-- 2. JOB SCORING PROFILES (Dynamic benchmarking per job)
-- ============================================================================

CREATE TABLE IF NOT EXISTS job_scoring_profiles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id INTEGER NOT NULL UNIQUE,
    technical_weight REAL DEFAULT 0.7,
    psychometric_weight REAL DEFAULT 0.3,
    min_passing_score REAL DEFAULT 70.0,
    skill_thresholds TEXT,  -- JSON: {"Python": 75, "JavaScript": 60}
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (job_id) REFERENCES job_descriptions(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_job_scoring_profiles ON job_scoring_profiles(job_id);

-- ============================================================================
-- 3. QUESTION BANK (Admin-managed question repository)
-- ============================================================================

CREATE TABLE IF NOT EXISTS question_bank (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_text TEXT NOT NULL,
    question_type TEXT NOT NULL,  -- 'mcq', 'coding', 'psychometric'
    category TEXT NOT NULL,  -- 'Python', 'JavaScript', 'System Design', etc.
    difficulty TEXT DEFAULT 'intermediate',  -- 'easy', 'intermediate', 'hard'
    required_skills TEXT,  -- JSON array of skills
    options TEXT,  -- JSON: For MCQ only, {"A": "...", "B": "...", ...}
    correct_answer TEXT,  -- For MCQ
    code_starter TEXT,  -- For coding problems
    test_cases TEXT,  -- JSON array of test cases
    expected_solution TEXT,  -- Reference solution for coding
    trait TEXT,  -- For psychometric (leadership, teamwork, etc.)
    job_specific_keywords TEXT,  -- JSON: keywords this question targets
    is_active BOOLEAN DEFAULT true,
    created_by_id INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (created_by_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_question_bank_type ON question_bank(question_type);
CREATE INDEX IF NOT EXISTS idx_question_bank_category ON question_bank(category);
CREATE INDEX IF NOT EXISTS idx_question_bank_difficulty ON question_bank(difficulty);

-- ============================================================================
-- 4. EMAIL TEMPLATES (Admin-managed email customization)
-- ============================================================================

CREATE TABLE IF NOT EXISTS email_templates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_name TEXT NOT NULL UNIQUE,  -- 'assessment_invite', 'rejection', 'offer', etc.
    subject TEXT NOT NULL,
    body TEXT NOT NULL,  -- HTML template with {{variable}} placeholders
    variables TEXT,  -- JSON: ["candidate_name", "assessment_link", "job_title"]
    is_default BOOLEAN DEFAULT false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO email_templates (template_name, subject, body, variables, is_default) VALUES
('assessment_invite', 'Your Assessment - {{job_title}}', 
'<p>Hi {{candidate_name}},</p><p>You have been invited to complete an assessment for the {{job_title}} position.</p><p><a href="{{assessment_link}}">Start Assessment</a></p>',
'["candidate_name", "job_title", "assessment_link"]', true),
('rejection', 'Application Status Update', 
'<p>Hi {{candidate_name}},</p><p>Thank you for your interest. We have decided to move forward with other candidates.</p>',
'["candidate_name"]', true),
('offer', 'Congratulations - Job Offer', 
'<p>Hi {{candidate_name}},</p><p>We are pleased to offer you the {{job_title}} position.</p>',
'["candidate_name", "job_title"]', true);

-- ============================================================================
-- 5. ASSESSMENT TEMPLATE LIBRARY
-- ============================================================================

CREATE TABLE IF NOT EXISTS assessment_templates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_name TEXT NOT NULL UNIQUE,
    description TEXT,
    role_type TEXT NOT NULL,  -- 'Software Engineer', 'Data Scientist', etc.
    difficulty_level TEXT DEFAULT 'intermediate',
    mcq_count INTEGER DEFAULT 10,
    coding_count INTEGER DEFAULT 1,
    psychometric_count INTEGER DEFAULT 3,
    time_limit_minutes INTEGER DEFAULT 60,
    tech_weight REAL DEFAULT 0.7,
    psych_weight REAL DEFAULT 0.3,
    is_default BOOLEAN DEFAULT false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO assessment_templates (template_name, description, role_type, difficulty_level, mcq_count, coding_count, psychometric_count, time_limit_minutes, is_default) VALUES
('SWE_Junior', 'Junior Software Engineer Assessment', 'Software Engineer', 'easy', 8, 1, 3, 45, true),
('SWE_Mid', 'Mid-Level Software Engineer Assessment', 'Software Engineer', 'intermediate', 10, 1, 3, 60, true),
('SWE_Senior', 'Senior Software Engineer Assessment', 'Software Engineer', 'hard', 12, 2, 3, 90, true),
('DS_Junior', 'Junior Data Scientist Assessment', 'Data Scientist', 'intermediate', 10, 1, 3, 60, true),
('DS_Senior', 'Senior Data Scientist Assessment', 'Data Scientist', 'hard', 12, 2, 3, 90, true);

-- ============================================================================
-- 6. ADMIN AUDIT LOG
-- ============================================================================

CREATE TABLE IF NOT EXISTS admin_audit_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id INTEGER NOT NULL,
    action_type TEXT NOT NULL,  -- 'create_user', 'delete_candidate', 'modify_job', etc.
    entity_type TEXT NOT NULL,  -- 'user', 'candidate', 'job', 'question', etc.
    entity_id INTEGER,
    old_values TEXT,  -- JSON of previous values
    new_values TEXT,  -- JSON of updated values
    description TEXT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (admin_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_log_admin ON admin_audit_log(admin_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_timestamp ON admin_audit_log(timestamp);

-- ============================================================================
-- 7. INTERVIEWER JOB POSTING PREFERENCES & SETTINGS
-- ============================================================================

CREATE TABLE IF NOT EXISTS interviewer_preferences (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interviewer_id INTEGER NOT NULL UNIQUE,
    default_assessment_template_id INTEGER,
    email_notifications BOOLEAN DEFAULT true,
    assessment_time_window_minutes INTEGER DEFAULT 30,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (interviewer_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (default_assessment_template_id) REFERENCES assessment_templates(id) ON DELETE SET NULL
);

-- ============================================================================
-- 8. ASSESSMENT RESULTS ENHANCED (Store AI recommendations)
-- ============================================================================

ALTER TABLE assessments
ADD COLUMN IF NOT EXISTS ai_recommendation TEXT,  -- JSON: AI-generated hiring recommendation
ADD COLUMN IF NOT EXISTS ai_confidence_score REAL,  -- 0-100
ADD COLUMN IF NOT EXISTS skill_gap_analysis TEXT,  -- JSON: identified skill gaps
ADD COLUMN IF NOT EXISTS interviewer_feedback TEXT,
ADD COLUMN IF NOT EXISTS final_decision_by_id INTEGER,
ADD COLUMN IF NOT EXISTS final_decision_date TIMESTAMP,
ADD CONSTRAINT fk_assessment_final_decision FOREIGN KEY (final_decision_by_id) REFERENCES users(id) ON DELETE SET NULL;

-- ============================================================================
-- 9. PROCTORING ENHANCED (Better violation tracking and analysis)
-- ============================================================================

ALTER TABLE proctoring_events
ADD COLUMN IF NOT EXISTS is_reviewed BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS violation_acknowledged BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS reviewer_id INTEGER,
ADD COLUMN IF NOT EXISTS reviewer_notes TEXT,
ADD CONSTRAINT fk_proctoring_reviewer FOREIGN KEY (reviewer_id) REFERENCES users(id) ON DELETE SET NULL;

-- ============================================================================
-- 10. ASSESSMENT PERFORMANCE HISTORY (For analytics and benchmarking)
-- ============================================================================

CREATE TABLE IF NOT EXISTS assessment_analytics (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id INTEGER NOT NULL,
    assessment_date DATE NOT NULL,
    total_assessments_completed INTEGER DEFAULT 0,
    average_technical_score REAL,
    average_psychometric_score REAL,
    average_overall_score REAL,
    pass_rate REAL,  -- % passing min_passing_score
    avg_completion_time_minutes INTEGER,
    total_violations_recorded INTEGER,
    hired_count INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (job_id) REFERENCES job_descriptions(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_analytics_job ON assessment_analytics(job_id);
CREATE INDEX IF NOT EXISTS idx_analytics_date ON assessment_analytics(assessment_date);

-- ============================================================================
-- 11. PROCTORING SESSION ENHANCEMENTS
-- ============================================================================

ALTER TABLE scheduled_assessments
ADD COLUMN IF NOT EXISTS proctor_id INTEGER,
ADD COLUMN IF NOT EXISTS proctor_notes TEXT,
ADD COLUMN IF NOT EXISTS proctoring_quality_score REAL,
ADD CONSTRAINT fk_scheduled_proctor FOREIGN KEY (proctor_id) REFERENCES users(id) ON DELETE SET NULL;

-- ============================================================================
-- 12. ADD CONSTRAINTS AND INDEXES
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_job_descriptions_interviewer ON job_descriptions(created_by_id);
CREATE INDEX IF NOT EXISTS idx_job_descriptions_status ON job_descriptions(status);
CREATE INDEX IF NOT EXISTS idx_assessments_job ON assessments(job_id);
CREATE INDEX IF NOT EXISTS idx_assessments_final_decision ON assessments(final_decision_by_id);
CREATE INDEX IF NOT EXISTS idx_scheduled_assessments_proctor ON scheduled_assessments(proctor_id);

-- ============================================================================
-- 13. UPDATE EXISTING ASSESSMENTS TABLE CONSTRAINT
-- ============================================================================

-- Link existing assessments to job_descriptions if not already linked
-- This is handled in the migration script, not here as it requires data logic

COMMIT;
