-- Migration: Add missing tables and columns for enhanced dashboard features
-- Date: 2026-01-31
-- Purpose: Fix missing database schema elements referenced in admin/interviewer/proctor routes

-- ============================================================================
-- ADD MISSING COLUMNS TO EXISTING TABLES
-- ============================================================================

-- Add missing columns to job_descriptions table
ALTER TABLE job_descriptions ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active';
ALTER TABLE job_descriptions ADD COLUMN IF NOT EXISTS created_by_id INTEGER REFERENCES users(id);
ALTER TABLE job_descriptions ADD COLUMN IF NOT EXISTS last_modified_by_id INTEGER REFERENCES users(id);
ALTER TABLE job_descriptions ADD COLUMN IF NOT EXISTS is_archived BOOLEAN DEFAULT FALSE;
ALTER TABLE job_descriptions ADD COLUMN IF NOT EXISTS skill_taxonomy TEXT;
ALTER TABLE job_descriptions ADD COLUMN IF NOT EXISTS role_complexity_level TEXT;
ALTER TABLE job_descriptions ADD COLUMN IF NOT EXISTS ai_refined_description TEXT;
ALTER TABLE job_descriptions ADD COLUMN IF NOT EXISTS ideal_candidate_profile TEXT;

-- Add missing columns to proctoring_events table
ALTER TABLE proctoring_events ADD COLUMN IF NOT EXISTS is_reviewed BOOLEAN DEFAULT FALSE;
ALTER TABLE proctoring_events ADD COLUMN IF NOT EXISTS reviewer_id INTEGER REFERENCES users(id);
ALTER TABLE proctoring_events ADD COLUMN IF NOT EXISTS reviewer_notes TEXT;
ALTER TABLE proctoring_events ADD COLUMN IF NOT EXISTS violation_acknowledged BOOLEAN DEFAULT FALSE;

-- Add missing columns to assessments table
ALTER TABLE assessments ADD COLUMN IF NOT EXISTS ai_recommendation TEXT;
ALTER TABLE assessments ADD COLUMN IF NOT EXISTS skill_gap_analysis TEXT;

-- Add missing columns to scheduled_assessments table
ALTER TABLE scheduled_assessments ADD COLUMN IF NOT EXISTS job_id INTEGER REFERENCES job_descriptions(id);
ALTER TABLE scheduled_assessments ADD COLUMN IF NOT EXISTS proctor_id INTEGER REFERENCES users(id);

-- ============================================================================
-- CREATE MISSING TABLES
-- ============================================================================

-- Job Scoring Profiles
CREATE TABLE IF NOT EXISTS job_scoring_profiles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id INTEGER NOT NULL REFERENCES job_descriptions(id) ON DELETE CASCADE,
    technical_weight REAL DEFAULT 0.7,
    psychometric_weight REAL DEFAULT 0.3,
    min_passing_score REAL DEFAULT 70.0,
    skill_thresholds TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(job_id)
);

-- Question Bank
CREATE TABLE IF NOT EXISTS question_bank (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_text TEXT NOT NULL,
    question_type TEXT NOT NULL, -- 'mcq', 'coding', 'psychometric'
    category TEXT NOT NULL, -- 'technical', 'behavioral', etc.
    difficulty TEXT DEFAULT 'intermediate', -- 'easy', 'intermediate', 'hard'
    required_skills TEXT, -- JSON array of skills
    options TEXT, -- JSON for MCQ options
    correct_answer TEXT,
    code_starter TEXT,
    test_cases TEXT, -- JSON for coding test cases
    expected_solution TEXT,
    trait TEXT, -- For psychometric questions
    job_specific_keywords TEXT, -- JSON array
    created_by_id INTEGER REFERENCES users(id),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Email Templates
CREATE TABLE IF NOT EXISTS email_templates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_name TEXT NOT NULL UNIQUE,
    subject TEXT NOT NULL,
    body_html TEXT NOT NULL,
    body_text TEXT,
    variables TEXT, -- JSON array of variable names like ['candidate_name', 'job_title']
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Assessment Templates
CREATE TABLE IF NOT EXISTS assessment_templates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    mcq_count INTEGER DEFAULT 10,
    coding_problems_count INTEGER DEFAULT 2,
    psychometric_count INTEGER DEFAULT 5,
    time_limit_minutes INTEGER DEFAULT 60,
    skills_focus TEXT, -- JSON array
    difficulty_distribution TEXT, -- JSON like {"easy": 30, "intermediate": 50, "hard": 20}
    created_by_id INTEGER REFERENCES users(id),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Admin Audit Log
CREATE TABLE IF NOT EXISTS admin_audit_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id INTEGER NOT NULL REFERENCES users(id),
    action TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id INTEGER,
    old_values TEXT, -- JSON
    new_values TEXT, -- JSON
    ip_address TEXT,
    user_agent TEXT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Assessment Analytics (for daily aggregations)
CREATE TABLE IF NOT EXISTS assessment_analytics (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id INTEGER REFERENCES job_descriptions(id) ON DELETE CASCADE,
    assessment_date DATE NOT NULL,
    total_assessments_completed INTEGER DEFAULT 0,
    average_overall_score REAL,
    average_technical_score REAL,
    average_psychometric_score REAL,
    pass_rate REAL,
    hired_count INTEGER DEFAULT 0,
    rejected_count INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(job_id, assessment_date)
);

-- Interviewer Preferences
CREATE TABLE IF NOT EXISTS interviewer_preferences (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interviewer_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    default_assessment_template_id INTEGER REFERENCES assessment_templates(id),
    email_notifications BOOLEAN DEFAULT TRUE,
    assessment_time_window_minutes INTEGER DEFAULT 30,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(interviewer_id)
);

-- ============================================================================
-- CREATE INDEXES
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_job_scoring_profiles_job ON job_scoring_profiles(job_id);
CREATE INDEX IF NOT EXISTS idx_question_bank_type ON question_bank(question_type);
CREATE INDEX IF NOT EXISTS idx_question_bank_category ON question_bank(category);
CREATE INDEX IF NOT EXISTS idx_question_bank_active ON question_bank(is_active);
CREATE INDEX IF NOT EXISTS idx_admin_audit_log_admin ON admin_audit_log(admin_id);
CREATE INDEX IF NOT EXISTS idx_admin_audit_log_action ON admin_audit_log(action);
CREATE INDEX IF NOT EXISTS idx_admin_audit_log_timestamp ON admin_audit_log(timestamp);
CREATE INDEX IF NOT EXISTS idx_assessment_analytics_job ON assessment_analytics(job_id);
CREATE INDEX IF NOT EXISTS idx_assessment_analytics_date ON assessment_analytics(assessment_date);
CREATE INDEX IF NOT EXISTS idx_proctoring_events_reviewed ON proctoring_events(is_reviewed);
CREATE INDEX IF NOT EXISTS idx_job_descriptions_status ON job_descriptions(status);
CREATE INDEX IF NOT EXISTS idx_job_descriptions_archived ON job_descriptions(is_archived);
CREATE INDEX IF NOT EXISTS idx_scheduled_assessments_job ON scheduled_assessments(job_id);
CREATE INDEX IF NOT EXISTS idx_scheduled_assessments_proctor ON scheduled_assessments(proctor_id);

-- ============================================================================
-- INSERT DEFAULT EMAIL TEMPLATES
-- ============================================================================

INSERT INTO email_templates (template_name, subject, body_html, body_text, variables)
VALUES 
    ('assessment_invitation', 
     'Assessment Invitation - {{job_title}}', 
     '<h1>Hello {{candidate_name}}</h1><p>You have been invited to take an assessment for {{job_title}}.</p><p>Please click the link below to start:</p><p><a href="{{assessment_link}}">Start Assessment</a></p>',
     'Hello {{candidate_name}}, You have been invited to take an assessment for {{job_title}}. Please use this link: {{assessment_link}}',
     '["candidate_name", "job_title", "assessment_link", "scheduled_time"]'),
    ('assessment_reminder',
     'Reminder: Your Assessment for {{job_title}}',
     '<h1>Reminder</h1><p>Dear {{candidate_name}}, this is a reminder that your assessment for {{job_title}} is scheduled for {{scheduled_time}}.</p>',
     'Dear {{candidate_name}}, this is a reminder that your assessment for {{job_title}} is scheduled for {{scheduled_time}}.',
     '["candidate_name", "job_title", "scheduled_time"]'),
    ('assessment_completed',
     'Assessment Completed - {{job_title}}',
     '<h1>Thank You!</h1><p>Dear {{candidate_name}}, thank you for completing your assessment for {{job_title}}. We will be in touch with the results soon.</p>',
     'Dear {{candidate_name}}, thank you for completing your assessment for {{job_title}}. We will be in touch with the results soon.',
     '["candidate_name", "job_title"]')
ON CONFLICT (template_name) DO NOTHING;
