-- ============================================================================
-- COMPREHENSIVE SQL MIGRATION FOR DASHBOARD FEATURES
-- Run these commands in your PostgreSQL database
-- ============================================================================

-- Step 1: ENHANCED JOB DESCRIPTIONS TABLE
-- ============================================================================
ALTER TABLE job_descriptions
ADD COLUMN IF NOT EXISTS created_by_id INTEGER,
ADD COLUMN IF NOT EXISTS ai_refined_description TEXT,
ADD COLUMN IF NOT EXISTS ideal_candidate_profile TEXT,
ADD COLUMN IF NOT EXISTS role_complexity_level TEXT DEFAULT 'intermediate',
ADD COLUMN IF NOT EXISTS skill_taxonomy TEXT,
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active',
ADD COLUMN IF NOT EXISTS is_archived BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS last_modified_by_id INTEGER,
ADD CONSTRAINT fk_job_created_by FOREIGN KEY (created_by_id) REFERENCES users(id) ON DELETE SET NULL,
ADD CONSTRAINT fk_job_modified_by FOREIGN KEY (last_modified_by_id) REFERENCES users(id) ON DELETE SET NULL;

-- Step 2: JOB SCORING PROFILES TABLE
-- ============================================================================
CREATE TABLE IF NOT EXISTS job_scoring_profiles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id INTEGER NOT NULL UNIQUE,
    technical_weight REAL DEFAULT 0.7,
    psychometric_weight REAL DEFAULT 0.3,
    min_passing_score REAL DEFAULT 70.0,
    skill_thresholds TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (job_id) REFERENCES job_descriptions(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_job_scoring_profiles ON job_scoring_profiles(job_id);

-- Step 3: QUESTION BANK TABLE
-- ============================================================================
CREATE TABLE IF NOT EXISTS question_bank (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_text TEXT NOT NULL,
    question_type TEXT NOT NULL,
    category TEXT NOT NULL,
    difficulty TEXT DEFAULT 'intermediate',
    required_skills TEXT,
    options TEXT,
    correct_answer TEXT,
    code_starter TEXT,
    test_cases TEXT,
    expected_solution TEXT,
    trait TEXT,
    job_specific_keywords TEXT,
    is_active BOOLEAN DEFAULT true,
    created_by_id INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (created_by_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_question_bank_type ON question_bank(question_type);
CREATE INDEX IF NOT EXISTS idx_question_bank_category ON question_bank(category);
CREATE INDEX IF NOT EXISTS idx_question_bank_difficulty ON question_bank(difficulty);

-- Step 4: EMAIL TEMPLATES TABLE
-- ============================================================================
CREATE TABLE IF NOT EXISTS email_templates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_name TEXT NOT NULL UNIQUE,
    subject TEXT NOT NULL,
    body TEXT NOT NULL,
    variables TEXT,
    is_default BOOLEAN DEFAULT false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert default email templates
INSERT INTO email_templates (template_name, subject, body, variables, is_default) VALUES
('assessment_invite', 'Your Assessment - {{job_title}}', 
'<p>Hi {{candidate_name}},</p><p>You have been invited to complete an assessment for the {{job_title}} position.</p><p><a href="{{assessment_link}}">Start Assessment</a></p><p>You have {{time_window}} minutes to begin the assessment.</p>',
'["candidate_name", "job_title", "assessment_link", "time_window"]', true),

('rejection', 'Application Status Update', 
'<p>Hi {{candidate_name}},</p><p>Thank you for your interest in the {{job_title}} position. After careful consideration, we have decided to move forward with other candidates.</p><p>Best regards,<br/>Recruitment Team</p>',
'["candidate_name", "job_title"]', true),

('offer', 'Congratulations - Job Offer', 
'<p>Hi {{candidate_name}},</p><p>We are pleased to offer you the {{job_title}} position. Your overall assessment score was {{score}}%.</p><p>Please reply to confirm your acceptance.</p><p>Best regards,<br/>Recruitment Team</p>',
'["candidate_name", "job_title", "score"]', true),

('assessment_reminder', 'Reminder: Your Assessment Starts Soon', 
'<p>Hi {{candidate_name}},</p><p>This is a reminder that your assessment for {{job_title}} is scheduled to start in {{minutes_remaining}} minutes.</p><p>Make sure you are in a quiet place with a stable internet connection.</p>',
'["candidate_name", "job_title", "minutes_remaining"]', true);

-- Step 5: ASSESSMENT TEMPLATES TABLE
-- ============================================================================
CREATE TABLE IF NOT EXISTS assessment_templates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_name TEXT NOT NULL UNIQUE,
    description TEXT,
    role_type TEXT NOT NULL,
    difficulty_level TEXT DEFAULT 'intermediate',
    mcq_count INTEGER DEFAULT 10,
    coding_count INTEGER DEFAULT 1,
    psychometric_count INTEGER DEFAULT 3,
    time_limit_minutes INTEGER DEFAULT 60,
    tech_weight REAL DEFAULT 0.7,
    psych_weight REAL DEFAULT 0.3,
    is_default BOOLEAN DEFAULT false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert default assessment templates
INSERT INTO assessment_templates (template_name, description, role_type, difficulty_level, mcq_count, coding_count, psychometric_count, time_limit_minutes, is_default) VALUES
('SWE_Junior', 'Junior Software Engineer Assessment', 'Software Engineer', 'easy', 8, 1, 3, 45, true),
('SWE_Mid', 'Mid-Level Software Engineer Assessment', 'Software Engineer', 'intermediate', 10, 1, 3, 60, true),
('SWE_Senior', 'Senior Software Engineer Assessment', 'Software Engineer', 'hard', 12, 2, 3, 90, true),
('DS_Junior', 'Junior Data Scientist Assessment', 'Data Scientist', 'intermediate', 10, 1, 3, 60, true),
('DS_Senior', 'Senior Data Scientist Assessment', 'Data Scientist', 'hard', 12, 2, 3, 90, true),
('PM_Standard', 'Product Manager Assessment', 'Product Manager', 'intermediate', 8, 0, 4, 45, true),
('QA_Standard', 'QA Engineer Assessment', 'QA Engineer', 'intermediate', 10, 1, 3, 60, true);

-- Step 6: ADMIN AUDIT LOG TABLE
-- ============================================================================
CREATE TABLE IF NOT EXISTS admin_audit_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id INTEGER NOT NULL,
    action_type TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id INTEGER,
    old_values TEXT,
    new_values TEXT,
    description TEXT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (admin_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_log_admin ON admin_audit_log(admin_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_timestamp ON admin_audit_log(timestamp);
CREATE INDEX IF NOT EXISTS idx_audit_log_action ON admin_audit_log(action_type);

-- Step 7: INTERVIEWER PREFERENCES TABLE
-- ============================================================================
CREATE TABLE IF NOT EXISTS interviewer_preferences (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interviewer_id INTEGER NOT NULL UNIQUE,
    default_assessment_template_id INTEGER,
    email_notifications BOOLEAN DEFAULT true,
    assessment_time_window_minutes INTEGER DEFAULT 30,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (interviewer_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (default_assessment_template_id) REFERENCES assessment_templates(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_interviewer_prefs ON interviewer_preferences(interviewer_id);

-- Step 8: ASSESSMENTS TABLE ENHANCEMENTS
-- ============================================================================
ALTER TABLE assessments
ADD COLUMN IF NOT EXISTS ai_recommendation TEXT,
ADD COLUMN IF NOT EXISTS ai_confidence_score REAL,
ADD COLUMN IF NOT EXISTS skill_gap_analysis TEXT,
ADD COLUMN IF NOT EXISTS interviewer_feedback TEXT,
ADD COLUMN IF NOT EXISTS final_decision_by_id INTEGER,
ADD COLUMN IF NOT EXISTS final_decision_date TIMESTAMP,
ADD CONSTRAINT fk_assessment_final_decision FOREIGN KEY (final_decision_by_id) REFERENCES users(id) ON DELETE SET NULL;

-- Step 9: PROCTORING ENHANCEMENTS
-- ============================================================================
ALTER TABLE proctoring_events
ADD COLUMN IF NOT EXISTS is_reviewed BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS violation_acknowledged BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS reviewer_id INTEGER,
ADD COLUMN IF NOT EXISTS reviewer_notes TEXT,
ADD CONSTRAINT fk_proctoring_reviewer FOREIGN KEY (reviewer_id) REFERENCES users(id) ON DELETE SET NULL;

-- Step 10: SCHEDULED ASSESSMENTS ENHANCEMENTS
-- ============================================================================
ALTER TABLE scheduled_assessments
ADD COLUMN IF NOT EXISTS job_id INTEGER,
ADD COLUMN IF NOT EXISTS proctor_id INTEGER,
ADD COLUMN IF NOT EXISTS proctor_notes TEXT,
ADD COLUMN IF NOT EXISTS proctoring_quality_score REAL,
ADD CONSTRAINT fk_scheduled_job FOREIGN KEY (job_id) REFERENCES job_descriptions(id) ON DELETE SET NULL,
ADD CONSTRAINT fk_scheduled_proctor FOREIGN KEY (proctor_id) REFERENCES users(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_scheduled_job ON scheduled_assessments(job_id);
CREATE INDEX IF NOT EXISTS idx_scheduled_proctor ON scheduled_assessments(proctor_id);

-- Step 11: ASSESSMENT ANALYTICS TABLE
-- ============================================================================
CREATE TABLE IF NOT EXISTS assessment_analytics (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id INTEGER NOT NULL,
    assessment_date DATE NOT NULL,
    total_assessments_completed INTEGER DEFAULT 0,
    average_technical_score REAL,
    average_psychometric_score REAL,
    average_overall_score REAL,
    pass_rate REAL,
    avg_completion_time_minutes INTEGER,
    total_violations_recorded INTEGER,
    hired_count INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (job_id) REFERENCES job_descriptions(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_analytics_job ON assessment_analytics(job_id);
CREATE INDEX IF NOT EXISTS idx_analytics_date ON assessment_analytics(assessment_date);
CREATE INDEX IF NOT EXISTS idx_analytics_job_date ON assessment_analytics(job_id, assessment_date);

-- Step 12: CREATE ADDITIONAL INDEXES FOR PERFORMANCE
-- ============================================================================
CREATE INDEX IF NOT EXISTS idx_job_descriptions_interviewer ON job_descriptions(created_by_id);
CREATE INDEX IF NOT EXISTS idx_job_descriptions_status ON job_descriptions(status);
CREATE INDEX IF NOT EXISTS idx_job_descriptions_archived ON job_descriptions(is_archived);
CREATE INDEX IF NOT EXISTS idx_assessments_job ON assessments(job_id);
CREATE INDEX IF NOT EXISTS idx_assessments_final_decision ON assessments(final_decision_by_id);
CREATE INDEX IF NOT EXISTS idx_assessments_ai_recommendation ON assessments(ai_recommendation);

-- Step 13: VERIFY ALL TABLES CREATED
-- ============================================================================
-- Run this query to verify all tables exist:
SELECT table_name FROM information_schema.tables 
WHERE table_schema = 'public' 
AND table_name IN (
  'job_descriptions', 'job_scoring_profiles', 'question_bank', 
  'email_templates', 'assessment_templates', 'admin_audit_log',
  'interviewer_preferences', 'assessment_analytics'
)
ORDER BY table_name;

-- ============================================================================
-- END OF MIGRATION
-- ============================================================================
